### ISSUE TITLE
Add a way to install shlink using an existing configuration file

### ISSUE THREAD

**Issue by hashworks** [shlinkio/shlink-installer#176]
#### Summary

It would be useful if one could provide a path to an existing configuration to the `install` script, just like with `update`. This is useful if one writes the `config/params/generated_config.php` file manually or generates it using configuration management software like `puppet` or `ansible` and just wants to initialize the database or download the GeoLite2 db.

It would also be useful if one could provide the path to the existing configuration with cli parameters, since stuff like `puppet` normally works non-interactively.

**Comment by hashworks** [comment]
> Can't you just use the update command then?

No, since it will fail if the database has never been initialized.

> maybe using env vars directly is the way to go, and just forgetting about the installer completely

This sounds reasonable, but one still needs a way to trigger the database initialization.

**Comment by acelaya** [comment]
This is the docker image entry point, which does not use the installer, but env bars, and everything is unattended there

https://github.com/shlinkio/shlink/blob/d75be372cb0adb401195d10ac5da15df75bdac7d/docker/docker-entrypoint.sh

Maybe you can do something similar.

**Comment by hashworks** [comment]
Ah! A documentation for those CLI params would be nice :)

**Comment by acelaya** [comment]
The database management commands are hidden from the public `list` command for historical reasons, but automating Shlink installs/updates is a very valid scenario.

I need to give it a thought and see if the shlink-installer is the right place to do that, or there should be some other tool or document explaining that.

**Comment by acelaya** [comment]
I have just implemented a new `init` command here, which is meant to allow automating Shlink installations.

It provides a consistent way to initialize the tooling around Shlink, which is now used by the `install` and `update` commands here, Shlink's docker entry point, and I will document it next so that it can also be used by userland scripts and automations.

```shell
> bin/shlink-installer init -h
Description:
  Initializes external dependencies required for Shlink to properly work, like DB, cache warmup, initial GeoLite DB download, etc

Usage:
  init [options]

Options:
      --skip-initialize-db        Skip the initial empty database creation. It will make this command fail on a later stage if the database was not created manually.
      --clear-db-cache            Clear the database metadata cache.
      --initial-api-key           Create and print initial admin API key.
      --update-roadrunner-binary  Try to update the RoadRunner binary. Providing this flag for a non-RoadRunner Shlink instance will result in an error.
      --skip-download-geolite     Skip downloading the initial GeoLite DB file. Shlink will try to download it the first time it needs to geolocate visits.
```

**Comment by acelaya** [comment]
Here are the docs https://shlink.io/documentation/command-line-interface/installation-tool/#init
